debug: True
wandb_logging: False
save_checkpoint: True
load_from_checkpoint: True
epoch_count: 15

mode: "eval"

model: "baseunet"
dataset: "PairedDatasetLabel"
loss_function: "BCELoss"
transformation: "label"

root_A: "data/cil-road-segmentation-2022/images"
root_B: "data/cil-road-segmentation-2022/groundtruth"
#root_A: "data/google/images"
#root_B: "data/google/masks"

checkpoint_root: "models/checkpoints"
checkpoint_load_pth: "models/checkpoints/atomic-pond-101"

image_height: 256 # They are actually 400 (We upsample/downsample)
image_width: 256 # They are actually 400 (We upsample/downsample)
batch_size: 1
epochs: 100
learning_rate: 0.0002
beta1: 0.5
beta2: 0.999
l1_lambda: 100
device: 'cuda'
num_workers: 1
pin_memory: False

seed: 1234