seed: 1234

batch_size: 4
num_workers: 12
pin_memoery: True

image_height: 400
image_width: 400

model: 'base-u-net'
load_from_checkpoint: False
checkpoint_path: "checkpoints/mymodel/run2/checkpoint.pth.tar"
loss_function: 'BCEWithLogitsLoss'
learning_rate: 1e-3
epochs: 20

wandb_logging: False