
debug: True
wandb_logging: True
save_checkpoint: True

load_from_checkpoint: False

model: "roadmap-gan"
dataset: "OriginalPix2Pix"
loss_function: "BCEWithLogitsLoss"

root_dir: "data/maps"
checkpoint_root: "models/checkpoints"

image_height: 256 # They are actually 300 (We upsample/downsample)
image_width: 256 # They are actually 300 (We upsample/downsample)
batch_size: 16
epochs: 200
learning_rate: 0.0002
beta1: 0.5
beta2: 0.999
l1_lambda: 100

device: 'cuda'
num_workers: 12
pin_memory: False

seed: 1234
